### ISSUE TITLE
font problem,cannot be displayed completely.

### ISSUE THREAD

**Issue by kingone51** [oxen-io/session-android#632]
There is a problem with the font and it cannot be displayed completely.
![IMG_20210704_103423](https://user-images.githubusercontent.com/51708777/124371340-77acc480-dcb3-11eb-8ed9-67e613d48c9d.jpg)

**Comment by hjubb** [comment]
I believe this is fixed now and will be out in a future update if not already :+1:

**Comment by kingone51** [comment]
> I believe this is fixed now and will be out in a future update if not already 👍

There are still problems😫

**Comment by hjubb** [comment]
this may be due to how the height is calculated by line count not taking into account line wraps, will look into this :+1:

**Comment by hjubb** [comment]
@kingone51 could you check if the latest release 1.11.5 fixes this on your end?

**Comment by kingone51** [comment]
problem remains. I use MIUI. I turn the system font big . Your software uses large system font, so the font is too large to display completely. This is the reason I think. It is suggested that the font size of the software is not consistent with the system. You should build a font adjustment in the software.

________________________________

**Comment by kingone51** [comment]
@hjubb problem remains. I use MIUI. I turn the system font big . Your software uses large system font, so the font is too large to display completely. This is the reason I think. It is suggested that the font size of the software is not consistent with the system. You should build a font adjustment in the software.
