### ISSUE TITLE
Disappearing messages do not work across multiple devices.

### ISSUE THREAD

**Issue by DonW16** [oxen-io/session-android#718]
**Code of conduct**

- [*] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Disappearing messages appear to be working for the receiver but not for the sender when using the Session Android app.

I have set disappearing messages to 1 day and many days have passed and I can still see the contents of the messages I've sent to my contact but not theirs.

I also use Session across multiple devices (Windows), the disappearing message function has worked fine, all messages get deleted after 1 day.

**To reproduce**

I'm unsure how I could reproduce this behavior.

If applicable, add screenshots or logs to help explain your problem.

![screenshot](https://user-images.githubusercontent.com/33807357/131876406-c402ed9e-c3fc-4074-a6d3-f55065f37172.PNG)

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S9
 - OS: Android 10
 - Session 1.11.8

**Additional context**

NA.

**Comment by hjubb** [comment]
To be clear, this is a message that was sent from another device you have linked, which has been synchronised to the android device and failing to delete?

**Comment by DonW16** [comment]
@hjubb yes that is correct, sorry for not being clear.

**Comment by DonW16** [comment]
I have also attached a screenshot of when I started the message thread.

![screenshot new](https://user-images.githubusercontent.com/33807357/132185314-b0ff2564-ad1c-4f22-b190-6e5e3c2bfb48.PNG)

**Comment by hjubb** [comment]
@DonW16  This should be fixed in 1.11.10, let me know and I'll close this issue

**Comment by hjubb** [comment]
Closing as this should now be fixed, let me know if it still has issues and I'll re-open it

**Comment by DonW16** [comment]
Hi @hjubb, I've updated Session to version 1.11.10, however the chat threads are still remaining? It's like the disappear timer is not getting activated?

**Comment by hjubb** [comment]
Does it happen just for the previous messages before this update or continues going forward from new messages?

**Comment by hjubb** [comment]
with a longer message expiry timer like 1 day or more it might not appear as anything is happening but would be good to confirm those things

**Comment by DonW16** [comment]
Do I can confirm the disappearing messages do now disappear for messages sent on Session 1.11.10 however all of the messages sent before this version are still present on the device (the timer has not started?). If they're any logs or more information I can give to help with this problem please let me know.

A temp fix is to ask your contact to delete and re-add your Session ID and for you to do the same. 😑

**Comment by hjubb** [comment]
Thanks for confirming, I'll look at making those messages clear out from before the update as well. I suppose you would only need to delete the messages not the actual contact itself, but I understand that's still pretty frustrating / undesirable. Thanks for checking back and updating

**Comment by DonW16** [comment]
Another update, my contact that is using Apple devices to communicate with sometimes the disappearing messages work and sometimes don't.

**Comment by DonW16** [comment]
Final update, in regards to disappearing messages, I don't think it a Session only problem however the problem does occur more in Session, the problem I've stated above has been replicated in Signal. Disappearing messages work on the desktop side but are still present on the mobile device, once the information of the message is viewed the timer starts apparently? 

I've attached photos showing the problem.

![Screenshot_20220115-093108_Signal](https://user-images.githubusercontent.com/33807357/149617150-9b26c598-b54b-440d-abc7-b5d47c7866cc.jpg)
![Screenshot_20220115-093111_Signal](https://user-images.githubusercontent.com/33807357/149617153-1ce47640-5bb0-43e8-ab78-4d16c8944ca3.jpg)

**Comment by tcely** [comment]
I think it would be really useful to have three types of disappearing messages:

1) sent messages that start the timer immediately after the first delivery confirmation.

2) received messages that start the timer immediately after confirming delivery.

3) delete after reading messages that start the timer immediately after a message is first displayed in the user interface.

The first type would help with this issue, as you would keep a synchronized copy of the sent message on all your devices and the timer would be included with the message. Every device just needs to update the state of that message as having been delivered as of a certain time to "start" the timer until it is removed.

The second type is for recipient devices and has the timer also included with the message. It needs to know the timestamp when the delivery of that message was first confirmed to calculate the expiration value.

The third type, also works for recipients and includes the timer value with the message. It needs to be wrapped in the UI though, so that the user can see that they have a "burn after reading" message waiting and when it was received. Then the timer starts when the user first removes that wrapper. This "unwrapped" timestamp needs to be synchronized to all the recipient's devices so that they can calculate the appropriate expiration timestamp.
